apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test-network
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp1s0",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "addresses": [{ "address": "192.168.122.150/24" }]
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: >-
      [{
        "name": "test-network",
        "interface": "n2",
        "default-route": ["192.168.122.1"],
        "gateway": "192.168.122.1"
      }]
spec:
  nodeSelector:
    kubernetes.io/hostname: core5g
  containers:
    - name: samplepod
      command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
      image: alpine
      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"
